version: "3.5"

services:
  request_counter:
    build:
      context: ../..
      dockerfile: ./build/package/Dockerfile
    environment:
      APP_REDIS_HOST: redis
      APP_REDIS_PORT: 6379
      APP_REDIS_COUNTER_KEY: cluster_count
      APP_SERVER_PORT: 8083
      APP_INIT_DEBUG: true
    expose:
      - "8083"
    deploy:
      replicas: 3
    depends_on:
      - redis
    networks:
      - requestcounter
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - requestcounter
  load_balancer:
    image: nginx:1.25-alpine
    ports:
      - "8083:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - request_counter
    networks:
      - requestcounter

networks:
  requestcounter: